//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderLincWS.AuthenticationWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthenticationWS.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VersionControl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool VersionControl(out string ErroMessage, string VersionMajor, string VersionMinor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        OrderLincWS.AuthenticationWS.DTOMobileAccount Login(string mUserName, string mPassword, string mDeviceNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterDevice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        OrderLincWS.AuthenticationWS.DTOMobileAccount RegisterDevice(string mUserName, string mPassword, string mDeviceNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UnRegisterDevice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UnRegisterDevice(string mUserName, string mPassword);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DTOMobileAccount : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long accountIDField;
        
        private long refIDField;
        
        private int accountTypeIDField;
        
        private int orgUnitIDField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string deviceNoField;
        
        private int roleIDField;
        
        private long addressIDField;
        
        private long contactIDField;
        
        private bool lockoutField;
        
        private string lastIpAddressField;
        
        private System.Nullable<System.DateTime> dateLockoutField;
        
        private System.Nullable<System.DateTime> lastLoginDateField;
        
        private System.DateTime dateCreatedField;
        
        private System.DateTime dateUpdatedField;
        
        private System.Nullable<System.DateTime> expiryDateField;
        
        private System.Nullable<System.DateTime> dateActivatedField;
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        private string lastNameField;
        
        private string firstNameField;
        
        private string emailField;
        
        private string accountTypeTextField;
        
        private string serverUrlField;
        
        private string logoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long AccountID {
            get {
                return this.accountIDField;
            }
            set {
                this.accountIDField = value;
                this.RaisePropertyChanged("AccountID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long RefID {
            get {
                return this.refIDField;
            }
            set {
                this.refIDField = value;
                this.RaisePropertyChanged("RefID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int AccountTypeID {
            get {
                return this.accountTypeIDField;
            }
            set {
                this.accountTypeIDField = value;
                this.RaisePropertyChanged("AccountTypeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int OrgUnitID {
            get {
                return this.orgUnitIDField;
            }
            set {
                this.orgUnitIDField = value;
                this.RaisePropertyChanged("OrgUnitID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DeviceNo {
            get {
                return this.deviceNoField;
            }
            set {
                this.deviceNoField = value;
                this.RaisePropertyChanged("DeviceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int RoleID {
            get {
                return this.roleIDField;
            }
            set {
                this.roleIDField = value;
                this.RaisePropertyChanged("RoleID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long AddressID {
            get {
                return this.addressIDField;
            }
            set {
                this.addressIDField = value;
                this.RaisePropertyChanged("AddressID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public long ContactID {
            get {
                return this.contactIDField;
            }
            set {
                this.contactIDField = value;
                this.RaisePropertyChanged("ContactID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool Lockout {
            get {
                return this.lockoutField;
            }
            set {
                this.lockoutField = value;
                this.RaisePropertyChanged("Lockout");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string LastIpAddress {
            get {
                return this.lastIpAddressField;
            }
            set {
                this.lastIpAddressField = value;
                this.RaisePropertyChanged("LastIpAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<System.DateTime> DateLockout {
            get {
                return this.dateLockoutField;
            }
            set {
                this.dateLockoutField = value;
                this.RaisePropertyChanged("DateLockout");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<System.DateTime> LastLoginDate {
            get {
                return this.lastLoginDateField;
            }
            set {
                this.lastLoginDateField = value;
                this.RaisePropertyChanged("LastLoginDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public System.DateTime DateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
                this.RaisePropertyChanged("DateCreated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public System.DateTime DateUpdated {
            get {
                return this.dateUpdatedField;
            }
            set {
                this.dateUpdatedField = value;
                this.RaisePropertyChanged("DateUpdated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<System.DateTime> ExpiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
                this.RaisePropertyChanged("ExpiryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<System.DateTime> DateActivated {
            get {
                return this.dateActivatedField;
            }
            set {
                this.dateActivatedField = value;
                this.RaisePropertyChanged("DateActivated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("StartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("EndDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string AccountTypeText {
            get {
                return this.accountTypeTextField;
            }
            set {
                this.accountTypeTextField = value;
                this.RaisePropertyChanged("AccountTypeText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string ServerUrl {
            get {
                return this.serverUrlField;
            }
            set {
                this.serverUrlField = value;
                this.RaisePropertyChanged("ServerUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string Logo {
            get {
                return this.logoField;
            }
            set {
                this.logoField = value;
                this.RaisePropertyChanged("Logo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : OrderLincWS.AuthenticationWS.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<OrderLincWS.AuthenticationWS.Service1Soap>, OrderLincWS.AuthenticationWS.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool VersionControl(out string ErroMessage, string VersionMajor, string VersionMinor) {
            return base.Channel.VersionControl(out ErroMessage, VersionMajor, VersionMinor);
        }
        
        public OrderLincWS.AuthenticationWS.DTOMobileAccount Login(string mUserName, string mPassword, string mDeviceNo) {
            return base.Channel.Login(mUserName, mPassword, mDeviceNo);
        }
        
        public OrderLincWS.AuthenticationWS.DTOMobileAccount RegisterDevice(string mUserName, string mPassword, string mDeviceNo) {
            return base.Channel.RegisterDevice(mUserName, mPassword, mDeviceNo);
        }
        
        public bool UnRegisterDevice(string mUserName, string mPassword) {
            return base.Channel.UnRegisterDevice(mUserName, mPassword);
        }
    }
}
