//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSTester.ws_OrderLinc {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://4solutions.co.au/", ConfigurationName="ws_OrderLinc.mobileservicesSoap")]
    public interface mobileservicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://4solutions.co.au/IsOnline", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool IsOnline();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://4solutions.co.au/EmailNotification", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool EmailNotification(out string ErrorMessage, string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://4solutions.co.au/VersionControl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool VersionControl(out string ErroMessage, string VersionMajor, string VersionMinor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://4solutions.co.au/GetReferenceData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetReferenceData(long salesOrgNo, long repAccountNo);
        
        // CODEGEN: Parameter 'imageArray' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://4solutions.co.au/SubmitOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WSTester.ws_OrderLinc.SubmitOrderResponse SubmitOrder(WSTester.ws_OrderLinc.SubmitOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://4solutions.co.au/CreateError", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int CreateError();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://4solutions.co.au/")]
    public partial class DTOOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long orderIDField;
        
        private long salesOrgIDField;
        
        private long customerIDField;
        
        private long salesRepAccountIDField;
        
        private long providerIDField;
        
        private int providerWarehouseIDField;
        
        private System.DateTime orderDateField;
        
        private System.Nullable<System.DateTime> deliveryDateField;
        
        private System.Nullable<System.DateTime> invoiceDateField;
        
        private int sYSOrderStatusIDField;
        
        private string orderNumberField;
        
        private System.Nullable<System.DateTime> receivedDateField;
        
        private System.Nullable<System.DateTime> releaseDateField;
        
        private bool isSentField;
        
        private bool isHeldField;
        
        private System.DateTime dateCreatedField;
        
        private System.DateTime dateUpdatedField;
        
        private long createdByUserIDField;
        
        private long updatedByUserIDField;
        
        private System.Nullable<System.DateTime> holdUntilDateField;
        
        private bool isMobileField;
        
        private string orderGUIDField;
        
        private string providerCustomerCodeField;
        
        private DTOOrderLine[] orderLineField;
        
        private string sYSOrderStatusTextField;
        
        private string customerNameField;
        
        private string providerNameField;
        
        private string createdByNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long OrderID {
            get {
                return this.orderIDField;
            }
            set {
                this.orderIDField = value;
                this.RaisePropertyChanged("OrderID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long SalesOrgID {
            get {
                return this.salesOrgIDField;
            }
            set {
                this.salesOrgIDField = value;
                this.RaisePropertyChanged("SalesOrgID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("CustomerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long SalesRepAccountID {
            get {
                return this.salesRepAccountIDField;
            }
            set {
                this.salesRepAccountIDField = value;
                this.RaisePropertyChanged("SalesRepAccountID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long ProviderID {
            get {
                return this.providerIDField;
            }
            set {
                this.providerIDField = value;
                this.RaisePropertyChanged("ProviderID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ProviderWarehouseID {
            get {
                return this.providerWarehouseIDField;
            }
            set {
                this.providerWarehouseIDField = value;
                this.RaisePropertyChanged("ProviderWarehouseID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime OrderDate {
            get {
                return this.orderDateField;
            }
            set {
                this.orderDateField = value;
                this.RaisePropertyChanged("OrderDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<System.DateTime> DeliveryDate {
            get {
                return this.deliveryDateField;
            }
            set {
                this.deliveryDateField = value;
                this.RaisePropertyChanged("DeliveryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<System.DateTime> InvoiceDate {
            get {
                return this.invoiceDateField;
            }
            set {
                this.invoiceDateField = value;
                this.RaisePropertyChanged("InvoiceDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int SYSOrderStatusID {
            get {
                return this.sYSOrderStatusIDField;
            }
            set {
                this.sYSOrderStatusIDField = value;
                this.RaisePropertyChanged("SYSOrderStatusID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string OrderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
                this.RaisePropertyChanged("OrderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<System.DateTime> ReceivedDate {
            get {
                return this.receivedDateField;
            }
            set {
                this.receivedDateField = value;
                this.RaisePropertyChanged("ReceivedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<System.DateTime> ReleaseDate {
            get {
                return this.releaseDateField;
            }
            set {
                this.releaseDateField = value;
                this.RaisePropertyChanged("ReleaseDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool IsSent {
            get {
                return this.isSentField;
            }
            set {
                this.isSentField = value;
                this.RaisePropertyChanged("IsSent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool IsHeld {
            get {
                return this.isHeldField;
            }
            set {
                this.isHeldField = value;
                this.RaisePropertyChanged("IsHeld");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public System.DateTime DateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
                this.RaisePropertyChanged("DateCreated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public System.DateTime DateUpdated {
            get {
                return this.dateUpdatedField;
            }
            set {
                this.dateUpdatedField = value;
                this.RaisePropertyChanged("DateUpdated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public long CreatedByUserID {
            get {
                return this.createdByUserIDField;
            }
            set {
                this.createdByUserIDField = value;
                this.RaisePropertyChanged("CreatedByUserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public long UpdatedByUserID {
            get {
                return this.updatedByUserIDField;
            }
            set {
                this.updatedByUserIDField = value;
                this.RaisePropertyChanged("UpdatedByUserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<System.DateTime> HoldUntilDate {
            get {
                return this.holdUntilDateField;
            }
            set {
                this.holdUntilDateField = value;
                this.RaisePropertyChanged("HoldUntilDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public bool IsMobile {
            get {
                return this.isMobileField;
            }
            set {
                this.isMobileField = value;
                this.RaisePropertyChanged("IsMobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string OrderGUID {
            get {
                return this.orderGUIDField;
            }
            set {
                this.orderGUIDField = value;
                this.RaisePropertyChanged("OrderGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string ProviderCustomerCode {
            get {
                return this.providerCustomerCodeField;
            }
            set {
                this.providerCustomerCodeField = value;
                this.RaisePropertyChanged("ProviderCustomerCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=23)]
        public DTOOrderLine[] OrderLine {
            get {
                return this.orderLineField;
            }
            set {
                this.orderLineField = value;
                this.RaisePropertyChanged("OrderLine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string SYSOrderStatusText {
            get {
                return this.sYSOrderStatusTextField;
            }
            set {
                this.sYSOrderStatusTextField = value;
                this.RaisePropertyChanged("SYSOrderStatusText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
                this.RaisePropertyChanged("CustomerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string ProviderName {
            get {
                return this.providerNameField;
            }
            set {
                this.providerNameField = value;
                this.RaisePropertyChanged("ProviderName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string CreatedByName {
            get {
                return this.createdByNameField;
            }
            set {
                this.createdByNameField = value;
                this.RaisePropertyChanged("CreatedByName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://4solutions.co.au/")]
    public partial class DTOOrderLine : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long orderLineIDField;
        
        private long orderIDField;
        
        private int lineNumField;
        
        private long productIDField;
        
        private float orderQtyField;
        
        private float despatchQtyField;
        
        private string uOMField;
        
        private float orderPriceField;
        
        private float despatchPriceField;
        
        private string itemStatusField;
        
        private string errorTextField;
        
        private string productCodeField;
        
        private string primarySKUField;
        
        private string productNameField;
        
        private string gTINCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long OrderLineID {
            get {
                return this.orderLineIDField;
            }
            set {
                this.orderLineIDField = value;
                this.RaisePropertyChanged("OrderLineID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long OrderID {
            get {
                return this.orderIDField;
            }
            set {
                this.orderIDField = value;
                this.RaisePropertyChanged("OrderID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int LineNum {
            get {
                return this.lineNumField;
            }
            set {
                this.lineNumField = value;
                this.RaisePropertyChanged("LineNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long ProductID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
                this.RaisePropertyChanged("ProductID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public float OrderQty {
            get {
                return this.orderQtyField;
            }
            set {
                this.orderQtyField = value;
                this.RaisePropertyChanged("OrderQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public float DespatchQty {
            get {
                return this.despatchQtyField;
            }
            set {
                this.despatchQtyField = value;
                this.RaisePropertyChanged("DespatchQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string UOM {
            get {
                return this.uOMField;
            }
            set {
                this.uOMField = value;
                this.RaisePropertyChanged("UOM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public float OrderPrice {
            get {
                return this.orderPriceField;
            }
            set {
                this.orderPriceField = value;
                this.RaisePropertyChanged("OrderPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public float DespatchPrice {
            get {
                return this.despatchPriceField;
            }
            set {
                this.despatchPriceField = value;
                this.RaisePropertyChanged("DespatchPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ItemStatus {
            get {
                return this.itemStatusField;
            }
            set {
                this.itemStatusField = value;
                this.RaisePropertyChanged("ItemStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ErrorText {
            get {
                return this.errorTextField;
            }
            set {
                this.errorTextField = value;
                this.RaisePropertyChanged("ErrorText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
                this.RaisePropertyChanged("ProductCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string PrimarySKU {
            get {
                return this.primarySKUField;
            }
            set {
                this.primarySKUField = value;
                this.RaisePropertyChanged("PrimarySKU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
                this.RaisePropertyChanged("ProductName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string GTINCode {
            get {
                return this.gTINCodeField;
            }
            set {
                this.gTINCodeField = value;
                this.RaisePropertyChanged("GTINCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://4solutions.co.au/")]
    public partial class DTOContact : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long contactIDField;
        
        private string phoneField;
        
        private string faxField;
        
        private string mobileField;
        
        private string emailField;
        
        private string lastNameField;
        
        private string firstNameField;
        
        private long createdByUserIDField;
        
        private long oldIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ContactID {
            get {
                return this.contactIDField;
            }
            set {
                this.contactIDField = value;
                this.RaisePropertyChanged("ContactID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
                this.RaisePropertyChanged("Fax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
                this.RaisePropertyChanged("Mobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long CreatedByUserID {
            get {
                return this.createdByUserIDField;
            }
            set {
                this.createdByUserIDField = value;
                this.RaisePropertyChanged("CreatedByUserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long OldID {
            get {
                return this.oldIDField;
            }
            set {
                this.oldIDField = value;
                this.RaisePropertyChanged("OldID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitOrder", WrapperNamespace="http://4solutions.co.au/", IsWrapped=true)]
    public partial class SubmitOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://4solutions.co.au/", Order=0)]
        public WSTester.ws_OrderLinc.DTOOrder order;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://4solutions.co.au/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] imageArray;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://4solutions.co.au/", Order=2)]
        public WSTester.ws_OrderLinc.DTOContact contact;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://4solutions.co.au/", Order=3)]
        public string uName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://4solutions.co.au/", Order=4)]
        public string uPW;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://4solutions.co.au/", Order=5)]
        public string deviceNo;
        
        public SubmitOrderRequest() {
        }
        
        public SubmitOrderRequest(WSTester.ws_OrderLinc.DTOOrder order, byte[] imageArray, WSTester.ws_OrderLinc.DTOContact contact, string uName, string uPW, string deviceNo) {
            this.order = order;
            this.imageArray = imageArray;
            this.contact = contact;
            this.uName = uName;
            this.uPW = uPW;
            this.deviceNo = deviceNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitOrderResponse", WrapperNamespace="http://4solutions.co.au/", IsWrapped=true)]
    public partial class SubmitOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://4solutions.co.au/", Order=0)]
        public long SubmitOrderResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://4solutions.co.au/", Order=1)]
        public string ServerMessage;
        
        public SubmitOrderResponse() {
        }
        
        public SubmitOrderResponse(long SubmitOrderResult, string ServerMessage) {
            this.SubmitOrderResult = SubmitOrderResult;
            this.ServerMessage = ServerMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface mobileservicesSoapChannel : WSTester.ws_OrderLinc.mobileservicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class mobileservicesSoapClient : System.ServiceModel.ClientBase<WSTester.ws_OrderLinc.mobileservicesSoap>, WSTester.ws_OrderLinc.mobileservicesSoap {
        
        public mobileservicesSoapClient() {
        }
        
        public mobileservicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public mobileservicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mobileservicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mobileservicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsOnline() {
            return base.Channel.IsOnline();
        }
        
        public bool EmailNotification(out string ErrorMessage, string Email) {
            return base.Channel.EmailNotification(out ErrorMessage, Email);
        }
        
        public bool VersionControl(out string ErroMessage, string VersionMajor, string VersionMinor) {
            return base.Channel.VersionControl(out ErroMessage, VersionMajor, VersionMinor);
        }
        
        public System.Data.DataSet GetReferenceData(long salesOrgNo, long repAccountNo) {
            return base.Channel.GetReferenceData(salesOrgNo, repAccountNo);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSTester.ws_OrderLinc.SubmitOrderResponse WSTester.ws_OrderLinc.mobileservicesSoap.SubmitOrder(WSTester.ws_OrderLinc.SubmitOrderRequest request) {
            return base.Channel.SubmitOrder(request);
        }
        
        public long SubmitOrder(WSTester.ws_OrderLinc.DTOOrder order, byte[] imageArray, WSTester.ws_OrderLinc.DTOContact contact, string uName, string uPW, string deviceNo, out string ServerMessage) {
            WSTester.ws_OrderLinc.SubmitOrderRequest inValue = new WSTester.ws_OrderLinc.SubmitOrderRequest();
            inValue.order = order;
            inValue.imageArray = imageArray;
            inValue.contact = contact;
            inValue.uName = uName;
            inValue.uPW = uPW;
            inValue.deviceNo = deviceNo;
            WSTester.ws_OrderLinc.SubmitOrderResponse retVal = ((WSTester.ws_OrderLinc.mobileservicesSoap)(this)).SubmitOrder(inValue);
            ServerMessage = retVal.ServerMessage;
            return retVal.SubmitOrderResult;
        }
        
        public int CreateError() {
            return base.Channel.CreateError();
        }
    }
}
